#############################################################################
# Makefile for building: Quick1.app/Contents/MacOS/Quick1
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Quick1.pro
# Template: app
# Command: /Users/xuenanli/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile Quick1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.7/clang_64/lib/QtQml.framework/Headers -I../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/xuenanli/Qt/5.7/clang_64/lib
QMAKE         = /Users/xuenanli/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Quick11.0.0
DISTDIR = /Users/xuenanli/Desktop/Quick1/.tmp/Quick11.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/xuenanli/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/xuenanli/Qt/5.7/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp \
		moc_states.cpp
OBJECTS       = main.o \
		qrc_qml.o \
		moc_states.o
DIST          = 1.png \
		../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Quick1.pro states.h \
		linedata.h main.cpp
QMAKE_TARGET  = Quick1
DESTDIR       = 
TARGET        = Quick1.app/Contents/MacOS/Quick1


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d Quick1.app/Contents/MacOS/ || mkdir -p Quick1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Quick1.pro ../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Quick1.pro \
		qml.qrc \
		../../Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Quick1.pro
../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../qt/5.7/clang_64/mkspecs/common/unix.conf:
../../qt/5.7/clang_64/mkspecs/common/mac.conf:
../../qt/5.7/clang_64/mkspecs/common/macx.conf:
../../qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../qt/5.7/clang_64/mkspecs/common/clang.conf:
../../qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Quick1.pro:
qml.qrc:
../../Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Quick1.pro

qmake_all: FORCE

Quick1.app/Contents/PkgInfo: 
	@test -d Quick1.app/Contents || mkdir -p Quick1.app/Contents
	@$(DEL_FILE) Quick1.app/Contents/PkgInfo
	@echo "APPL????" > Quick1.app/Contents/PkgInfo
Quick1.app/Contents/Resources/empty.lproj: 
	@test -d Quick1.app/Contents/Resources || mkdir -p Quick1.app/Contents/Resources
	@touch Quick1.app/Contents/Resources/empty.lproj
	
Quick1.app/Contents/Info.plist: 
	@test -d Quick1.app/Contents || mkdir -p Quick1.app/Contents
	@$(DEL_FILE) Quick1.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,oncelife.Quick1,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Quick1,g" -e "s,@LIBRARY@,Quick1,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Quick1.app/Contents/Info.plist

all: Makefile \
		Quick1.app/Contents/PkgInfo \
		Quick1.app/Contents/Resources/empty.lproj \
		Quick1.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents states.h linedata.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Quick1.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../Qt/5.7/clang_64/bin/rcc \
		Statecenter.qml \
		Line.qml \
		1.png \
		main.qml
	/Users/xuenanli/Qt/5.7/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_states.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_states.cpp
moc_states.cpp: ../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		states.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/xuenanli/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/xuenanli/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/xuenanli/Desktop/Quick1 -I/Users/xuenanli/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/xuenanli/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/xuenanli/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/xuenanli/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/xuenanli/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/xuenanli/Qt/5.7/clang_64/lib states.h -o moc_states.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		states.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		dataread.cpp \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QList \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		linedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_states.o: moc_states.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_states.o moc_states.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Quick1/bin || mkdir -p $(INSTALL_ROOT)/opt/Quick1/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Quick1/bin/Quick1.app
	
	-$(INSTALL_DIR) Quick1.app $(INSTALL_ROOT)/opt/Quick1/bin/Quick1.app
	-$(STRIP) $(INSTALL_ROOT)/opt/Quick1/bin/Quick1.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Quick1/bin/Quick1.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Quick1/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

